# Generated by Django 4.2.18 on 2025-02-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hems',
            field=models.IntegerField(default=0),
        ),
    ]
