# Generated by Django 4.2.18 on 2025-02-03 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='email',
        ),
    ]
