# Generated by Django 4.2.18 on 2025-02-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_alter_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.CharField(max_length=255),
        ),
    ]
