# Generated by Django 4.2.18 on 2025-02-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0007_sale_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
